### ISSUE TITLE
please consider changing Reinforced Armor indicator

### ISSUE THREAD

**Issue by AdjutantAvocado** [Zerthox/arcdps-food-reminder#27]
As of release v0.5.1, the reinforced armor column is indicated as a red "No" if the player doesn't need to refresh their Reinforced buff. That's kind of counterintuitive, I'd suggest changing it to a green "On" and red "Off", or green "Active" and red "Inactive".

**Comment by AdjutantAvocado** [comment]
clarification: out of combat only

**Comment by Zerthox** [comment]
The red "No" should be displayed when the Reinforced Armor buff is **not** applied to the player and the green "Yes" when it is applied. If "No" is displayed while the player has the Reinforced buff something went wrong.

**Comment by Zerthox** [comment]
Identified the issue. Refreshing Reinforced could apply the new buff before removing the old one, which caused the plugin to incorrectly think there was no Reinforced present on the player. Should be fixed in the next update.

**Comment by Stefanovicc** [comment]
> Identified the issue. Refreshing Reinforced could apply the new buff before removing the old one, which caused the plugin to incorrectly think there was no Reinforced present on the player. Should be fixed in the next update.

I'm still getting the message "Reinforced reminder!" even though I have the buff on. Am I doing something wrong?

**Comment by Zerthox** [comment]
> I'm still getting the message "Reinforced reminder!" even though I have the buff on. Am I doing something wrong?

What does the tracker window display? Default hotkey is Alt+Shift+F.

If it says Reinforced is not applied, check the log window: ArcDPS settings (Alt+Shift+T), About tab, check the log checkbox.
Under extensions you should be able to see the buff apply & remove events registered by the plugin.

**Comment by Stefanovicc** [comment]
> > I'm still getting the message "Reinforced reminder!" even though I have the buff on. Am I doing something wrong?
> 
> What does the tracker window display? Default hotkey is Alt+Shift+F.
> 
> If it says Reinforced is not applied, check the log window: ArcDPS settings (Alt+Shift+T), About tab, click the log checkbox. Under extensions you should be able to see the buff apply & remove events registered by the plugin.

Thanks for your reply.

I've just checked it. It says "YES" in the food tracker, but when I enter combat it changes to "NO" (while it's still active). Therefore it shows "After encounter" & "During encounter" that it's missing.

**Comment by Zerthox** [comment]
The log gives the impression Arc is delaying the buff apply in the plugin API until log end. But I am unable to reproduce this. Which ArcDPS version are you on?

**Comment by Stefanovicc** [comment]
> The log gives the impression Arc is delaying the buff apply in the plugin API until log end. But I am unable to reproduce this. Which ArcDPS version are you on?

Hmm weird. This is my version: arcdps 20220914.180323-454-x64
